### ISSUE TITLE
requirements.txt does not specify version numbers

### ISSUE THREAD

**Issue by yuvipanda** [halfak/Revision-Scoring#102]
It should be the output of 'pip freeze', which specifies exact versions.

**Comment by yuvipanda** [comment]
Same is true for ORES as well

**Comment by halfak** [comment]
Fixed in https://github.com/halfak/Revision-Scoring/releases/tag/v0.3.0 and https://github.com/halfak/Objective-Revision-Evaluation-Service/releases/tag/v0.1.0
