### ISSUE TITLE
Probability returned by SVC models is useless

### ISSUE THREAD

**Issue by halfak** [halfak/Revision-Scoring#45]
The probability returned by SVC models seems to be weighted by rate of input labels.  This is lame and causes problems that, in the case predicting low probability events, results in low-probability scores.  

For example, this doesn't make sense:

    642215410: {
        'prediction': True, 
        'probabilities': [0.75884553,  0.24115447]
    }

Note that the second probability which references "True" is 0.24 when it should at least be above 50%.

**Comment by he7d3r** [comment]
Is this something that could be fixed upstream?

**Comment by halfak** [comment]
Yes.  Three reasons I haven't tried to do that:

1. I still haven't figured out exactly what is going on (something about how the logistic regression is trained with for Platt Scaling). 
2. The fix will probably involve work on libsvm, the underlying C library.
3. If/when it does get fixed, this should still theoretically work just fine.

**Comment by halfak** [comment]
Oh yeah!  You can see my work here: http://nbviewer.ipython.org/github/halfak/Objective-Revision-Evaluation-Service/blob/ipython/ipython/Wat%20predict_proba.ipynb
