### ISSUE TITLE
Use stopwords to supplement Portuguese dictionary 

### ISSUE THREAD

**Issue by halfak** [halfak/Revision-Scoring#58]

**Comment by he7d3r** [comment]
@halfak: Wasn't this fixed by https://github.com/halfak/Revision-Scoring/commit/0afd3e260b1ca0574cf972e3e78bd270f6e49eaf#diff-4833742d6f628e1caf4f88196c95563fR3 ?

**Comment by halfak** [comment]
Regretfully, it doesn't.  [This line](https://github.com/halfak/Revision-Scoring/blob/master/revscoring/languages/portuguese.py#L203) should be changed to:

   if word.lower() in STOPWORDS: return False
