### ISSUE TITLE
Detect content namespaces other than the mainspace 

### ISSUE THREAD

**Issue by he7d3r** [halfak/Revision-Scoring#8]
Currently there is a [is_mainspace.py](https://github.com/halfak/Revision-Scoring/blob/master/revscores/features/is_mainspace.py#L11) to check if a page is in the main namespace. However, some wikis use [wgContentNamespaces](https://www.mediawiki.org/wiki/Manual:$wgContentNamespaces) (e.g. [arwiki](https://github.com/wikimedia/operations-mediawiki-config/blob/master/wmf-config/InitialiseSettings.php#L9776)) to define other namespaces which also have content. These should probably be treated the same way as the mainspace.

**Comment by halfak** [comment]
Change is merged.
